name: flutter_multi_formatter
description: A package of formatters for international phone numbers, credit / debit cards and a masked formatter
version: 2.10.2
homepage: https://github.com/caseyryan/flutter_multi_formatter

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: 3.3.8

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter